services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./web
    ports:
      - "8081:8081"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s